# Arquivo Docker Compose do Immich
# Nota: Este arquivo depende das variáveis definidas no arquivo `.env` no mesmo diretório.

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: docker.io/library/redis:6.2-alpine
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: unless-stopped
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", "shared_buffers=512MB", "-c", "row_security=off"]

volumes:
  model-cache:



# ================================
# Arquivo .env obrigatório
# ================================
#
# Copie o .env.example para .env
# e ajuste os valores.
#
# ================================



# ================================
# Acesso ao Immich
# ================================
#
# URL:
# http://localhost:2283
#
# Primeiro acesso:
#
# 1 - Acesse http://localhost:2283
# 2 - Crie o usuário administrador
# 3 - Comece a fazer upload das fotos
#
# ================================
