services:

  # ================================
  # Jellyfin - Media Server
  # ================================
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped

    ports:
      - "8096:8096"   # Interface Web

    volumes:
      # Configurações do Jellyfin
      - ./config:/config

      # Cache do Jellyfin
      - ./cache:/cache

      # Pasta com mídias (filmes, séries, músicas)
      - ./media:/media

    environment:
      - TZ=America/Sao_Paulo

  # ================================
  # Transmission - Torrent Client
  # ================================
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped

    ports:
      - "9091:9091"   # Interface Web
      - "51413:51413" # Porta de peer

    volumes:
      # Configurações do Transmission
      - ./transmission/config:/config

      # Downloads completados (já aparece no Jellyfin)
      - ./media/transmission:/downloads

    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
      - USER=admin
      - PASS=transmission



# ================================
# Pastas utilizadas
# ================================
#
# ./media
# → Armazena seus arquivos:
#    - Filmes
#    - Séries
#    - Músicas
#    - Vídeos
#    - transmission/ (downloads torrents)
#
# ./config
# → Configurações do Jellyfin
#    - Usuários
#    - Bibliotecas
#    - Metadados
#
# ./cache
# → Cache do sistema
#
# ./transmission/config
# → Configurações do Transmission
#
# Todas as pastas serão criadas automaticamente
# na mesma pasta do compose.yaml
#
# Faça backup principalmente da pasta:
# ./config
#
# ================================



# ================================
# Acesso
# ================================
#
# Jellyfin:
# http://localhost:8096
#
# Transmission:
# http://localhost:9091
#
# Primeiro acesso (Jellyfin):
#
# 1 - Criar usuário administrador
# 2 - Adicionar biblioteca
# 3 - Selecionar pasta:
#
# /media
#
# Depois disso, o Jellyfin irá
# identificar automaticamente os arquivos.
#
# ================================