services:

  # ================================
  # Jellyfin - Media Server
  # ================================
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped

    ports:
      - "8096:8096"

    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media

    environment:
      - TZ=America/Sao_Paulo

  # ================================
  # qBittorrent - Torrent Client
  # ================================
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped

    ports:
      - "9091:8080"
      - "6881:6881"
      - "6881:6881/udp"

    volumes:
      - ./qbittorrent/config:/config
      - ./media/qBittorrent:/downloads

    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - WEBUI_PORT=8080



# ================================
# Estrutura de Pastas
# ================================
#
# .
# ├── compose.yaml
# ├── cache/
# ├── config/
# ├── media/
# │   ├── Filmes/
# │   ├── Series/
# │   ├── Musicas/
# │   ├── Videos/
# │   └── qBittorrent/
# └── qbittorrent/
#     └── config/
#
# ================================



# ================================
# Acesso
# ================================
#
# Jellyfin:
# http://localhost:8096
#
# qBittorrent:
# http://localhost:9091
# Usuário: admin
# Senha: adminadmin
#
# ================================
