services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped

    ports:
      - "9443:9443"   # Interface Web (HTTPS)
      - "9000:9000"   # Interface Web (HTTP)

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:



# ================================
# Acesso ao Portainer
# ================================
#
# URL:
# https://localhost:9443
#
# Primeiro acesso:
#
# 1 - Acesse https://localhost:9443
# 2 - Crie o usuário administrador
# 3 - Conecte ao Docker local
#
# ================================
