server {
    listen 443 ssl http2;
    server_name localhost 192.168.2.100;

    ssl_certificate     /ssl/vaultwarden.crt;
    ssl_certificate_key /ssl/vaultwarden.key;

    location / {
        proxy_pass http://vaultwarden:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
